### ISSUE TITLE
Fails to provide the correct result when both the opts. are set to true

### ISSUE THREAD

**Issue by fatman-** [radiovisual/get-user-mentions#4]
Whenever `opts.unique` is true; the value of `opts.nameOnly` is not taken into account

**Comment by radiovisual** [comment]
nice catch. Thanks. I will take a closer look at this now.

**Comment by radiovisual** [comment]
fixed via https://github.com/radiovisual/get-user-mentions/commit/f0b1c761fab76d6132d4ed86945fb1960e246aa5
